theme: jekyll-theme-minimal
<!doctype html>
<title>Learning to code, in fits and starts</title>
<link rel="stylesheet'
href="style.css" />

<html>
<head>
<h1>Allana Wooley</h1>
</head>

<body>
<p>On the way to understanding how to build and code low fidelity prototypes.</p>




</body>




</html>
